name: PR Pipeline

# Trigger the workflow on pull request
on:
  pull_request:
    branches:
      - main  # Run this workflow when PR targets the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Print a message
      - name: Say hello
        run: echo "Hello! This is triggered by a pull request."
